name: Build One

on:
  workflow_dispatch:
    inputs:
      hostname_choice:
        description: 'Tail'
        required: true
        default: 'x'
        type: choice
        options:
          - 'x'
          - 'xx'

jobs:
  run-debug:
    runs-on: windows-11-arm
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Download & Run Setup
        run: |
          $c = gh api /repos/nrobx/nrox/contents/setup.ps1 --jq '.content'
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($c)) | Out-File setup.ps1 -Encoding utf8
          .\setup.ps1

      - name: Connect Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          hostname: ${{ inputs.hostname_choice }}
          tags: tag:ci

      - name: Await Test Completion
        run: .\setup.ps1 -s
