name: build-2

on: workflow_dispatch

jobs:
  run-debug:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Download & Run Setup
        run: |
          gh api /repos/nrobx/nrox/contents/setupm.sh --jq '.content' | base64 -d > ~/setupm.sh
          chmod +x ~/setupm.sh
          # ~/setupm.sh

      - name: Connect Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          hostname: xx
          tags: tag:ci
          args: --ssh

      - name: Await Test Completion
        run: ~/setupm.sh -s
