name: Build One

on:
  workflow_dispatch:
    inputs:
      hostname_choice:
        description: 'Tail'
        default: 'x'
        type: choice
        options:
          - 'x'
          - 'xx'

jobs:
  run-xx:
    runs-on: windows-2025
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:

      - name: Connect Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          hostname: ${{ inputs.hostname_choice }}
          tags: tag:ci

      - name: Download & Run Setup
        run: |
          gh repo clone nrobx/nrox -- -q
          .\nrox\setup.ps1

      - name: Await Test Completion
        run: .\nrox\setup.ps1 -s
