name: build-4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      TARGET: ${{ inputs.target }}
    steps:
      - name: Free disk
        run: |
          echo "Listing disk space before cleanup:"
          df -h
          sudo rm -rf \
            /usr/local/.ghcup \
            /usr/local/julia* \
            /usr/local/aws-cli \
            /usr/local/aws-sam-cli \
            /usr/local/n \
            /usr/local/sqlpackage \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift \
            /usr/share/miniconda \
            /usr/share/az_* \
            /usr/share/sbt \
            /opt/hostedtoolcache/CodeQL \
            /opt/hostedtoolcache/PyPy \
            /opt/hostedtoolcache/Ruby \
            /opt/hostedtoolcache/go \
            /opt/hostedtoolcache/Python \
            /opt/az \
            /opt/microsoft \
            /opt/google \
            /opt/pipx \
            /usr/lib/google-cloud-sdk \
            /usr/lib/heroku \
            /usr/lib/firefox \
            /usr/lib/mono \
            /usr/lib/llvm-1* \
            /home/linuxbrew
          docker system prune -af --volumes 2>/dev/null || true
          echo "Listing disk space after cleanup:"
          df -h

      - name: Install deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq \
            bc bison build-essential ccache curl flex g++-multilib gcc-multilib \
            git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf \
            lib32readline-dev lib32z1-dev libdw-dev libelf-dev libgnutls28-dev lz4 \
            libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync \
            schedtool squashfs-tools xsltproc xxd zip zlib1g-dev \
            lib32ncurses5-dev libncurses5 libncurses5-dev
          sudo apt-get install -y -qq python-is-python3
          sudo apt-get clean -qq
          sudo wget -q https://storage.googleapis.com/git-repo-downloads/repo -O /usr/local/bin/repo
          sudo chmod a+x /usr/local/bin/repo
          repo --version

      - name: Download assets
        run: |
          gh repo clone nrobx/nrox -- -q
          unzip -o nrox/vendor_keys.zip -d .
          unzip -o nrox/vrbe.zip -d .
          mv nrox/sync.sh .
          ./nrox/setup.sh
          rm -rf nrox

      - name: Connect Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          hostname: xxx
          tags: tag:ci
          args: --ssh

      - name: Init & Vendor keys
        run: ./sync.sh -s

      - name: Keep Alive
        if: ${{ inputs.debug }}
        run: |
          while true; do sleep 300; done
